version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Phnom_Penh"
    open-pull-requests-limit: 5
    target-branch: "main"
    labels:
      - "dependencies"

  - package-ecosystem: "cargo"
    directory: "/src-tauri"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:15"
      timezone: "Asia/Phnom_Penh"
    open-pull-requests-limit: 5
    target-branch: "main"
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:30"
      timezone: "Asia/Phnom_Penh"
    open-pull-requests-limit: 5
    target-branch: "main"
    labels:
      - "dependencies"
