[package]
name = "tauri-plugin-vault-source"
version = "0.1.0"
edition = "2021"
rust-version = "1.77.2"
links = "tauri-plugin-vault-source"

[lib]
crate-type = ["rlib"]

[dependencies]
serde = { version = "1", features = ["derive"] }
tauri = "2"
thiserror = "2"

[build-dependencies]
tauri-plugin = { version = "2", features = ["build"] }
